### ISSUE TITLE
Panic of provider related to SCM integrations resources

### ISSUE THREAD

**Issue by Soulou** [Scalingo/terraform-provider-scalingo#13]
```
2020-03-24T11:19:54.882+0100 [DEBUG] plugin.terraform-provider-scalingo: [DEBUG]2020/03/24 11:19:54 {"scm_repo_link":{"id":"5a5f159ef112e200108bda00","app_id":"[redacted]","linker":{"username":"soulou","email":"leo@[redacted","id":"us-968c2d64-c4ec-41c2-a939-145ac1a2f76e"},"url":"https://github.com","owner":"Scalingo","repo":"homepage","branch":"master","scm_type":"github","created_at":"2018-01-17T09:21:35.453Z","updated_at":"2020-03-24T10:19:54.825Z","auto_deploy_enabled":true,"auth_integration_uuid":"[redacted]","deploy_review_apps_enabled":false,"delete_on_close_enabled":true,"hours_before_delete_on_close":0,"delete_stale_enabled":false,"hours_before_delete_stale":0,"last_auto_deploy_at":"2020-03-21T15:11:16.788Z"}}
 runtime error: invalid memory address or nil pointer dereference
2020-03-24T11:19:54.884+0100 [DEBUG] plugin.terraform-provider-scalingo: [signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0xdee28f]
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: goroutine 15 [running]:
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: github.com/Scalingo/terraform-provider-scalingo/scalingo.resourceGithubLinkUpdate(0xc000105420, 0x10ea700, 0xc0004902c0, 0x24, 0x1b1fa20)
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 	/home/leo/Projects/Go/src/github.com/Scalingo/terraform-provider-scalingo/scalingo/resource_scalingo_github_link.go:199 +0x62f
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000488480, 0xc0000d12c0, 0xc00062efe0, 0x10ea700, 0xc0004902c0, 0xc00048ce01, 0xc0004b7740, 0x410723)
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 	/home/leo/Projects/Go/pkg/mod/github.com/hashicorp/terraform@v0.12.20/helper/schema/resource.go:311 +0x263
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000488600, 0xc0005558e0, 0xc0000d12c0, 0xc00062efe0, 0xc0004c6ce8, 0xc0004cc018, 0xf63d20)
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 	/home/leo/Projects/Go/pkg/mod/github.com/hashicorp/terraform@v0.12.20/helper/schema/provider.go:289 +0x99
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000010078, 0x138d1e0, 0xc0004b6150, 0xc0002fc9c0, 0xc000010078, 0xc0004b6150, 0xc000069a58)
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 	/home/leo/Projects/Go/pkg/mod/github.com/hashicorp/terraform@v0.12.20/helper/plugin/grpc_provider.go:885 +0x8c4
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10afec0, 0xc000010078, 0x138d1e0, 0xc0004b6150, 0xc0000d0a50, 0x0, 0x138d1e0, 0xc0004b6150, 0xc0000e8c00, 0x388)
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 	/home/leo/Projects/Go/pkg/mod/github.com/hashicorp/terraform@v0.12.20/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000086900, 0x139ac40, 0xc0000a3980, 0xc0004b8000, 0xc0001a09f0, 0x1af3660, 0x0, 0x0, 0x0)
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 	/home/leo/Projects/Go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:998 +0x46a
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: google.golang.org/grpc.(*Server).handleStream(0xc000086900, 0x139ac40, 0xc0000a3980, 0xc0004b8000, 0x0)
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 	/home/leo/Projects/Go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:1278 +0xd97
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000c6490, 0xc000086900, 0x139ac40, 0xc0000a3980, 0xc0004b8000)
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 	/home/leo/Projects/Go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:717 +0xbb
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-03-24T11:19:54.885+0100 [DEBUG] plugin.terraform-provider-scalingo: 	/home/leo/Projects/Go/pkg/mod/google.golang.org/grpc@v1.21.1/server.go:715 +0xa1
2020-03-24T11:19:54.890+0100 [DEBUG] plugin: plugin process exited: path=/home/leo/Projects/Go/bin/terraform-provider-scalingo pid=612303 error="exit status 2"
```

**Comment by EtienneM** [comment]
We need to investigate whether this is still the case or not

**Comment by Soulou** [comment]
```
╷
│ Error: Plugin did not respond                                                                                             
│ 
│   with module.infosec-vulreport[0].module.app.module.app.scalingo_github_link.default[0],           
│   on base/app/main.tf line 44, in resource "scalingo_github_link" "default":
│   44: resource "scalingo_github_link" "default" {         
│                                                                                                                           
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵                                        
                                                              
Stack trace from the terraform-provider-scalingo_v0.5.2 plugin:                                                 
                                                              
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xa9edd7]
                                                              
goroutine 309 [running]:                 
github.com/Scalingo/terraform-provider-scalingo/scalingo.resourceGithubLinkUpdate({0xd2d040, 0xc000581140}, 0xc0001f2580, {0xc1fce0, 0xc000392540})
        github.com/Scalingo/terraform-provider-scalingo/scalingo/resource_scalingo_github_link.go:200 +0x9f7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000392e00, {0xd2d040, 0xc000581140}, 0xd, {0xc1fce0, 0xc000392540})                                               
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000392e00, {0xd2d040, 0xc000581140}, 0xc0000cc680, 0xc0001f2400, {0xc1fce0, 0xc000392540})                                                                              
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:847 +0x9e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000381950, {0xd2cf98, 0xc0006a1900}, 0xc0006d9360)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0004268c0, {0xd2d040, 0xc000580840}, 0xc00042cbd0)          
        github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbf4f00, 0xc0004268c0}, {0xd2d040, 0xc000580840}, 0xc00031a3c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003a6700, {0xd3b328, 0xc0004a36c0}, 0xc00045bc20, 0xc0004ceba0, 0x1237f40, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc0003a6700, {0xd3b328, 0xc0004a36c0}, 0xc00045bc20, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1 
        google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-scalingo_v0.5.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue. 
```

Still present

**Comment by aurelien-reeves-scalingo** [comment]
The GithubLink structure defined in go-scalingo looks like the following:

```go
type GithubLink struct {
	ID                       string           `json:"id"`
	Linker                   GithubLinkLinker `json:"linker"`
	CreatedAt                time.Time        `json:"created_at"`
	UpdatedAt                time.Time        `json:"updated_at"`
	GithubSource             string           `json:"github_source"`
	GithubBranch             string           `json:"github_branch"`
	AutoDeployEnabled        bool             `json:"auto_deploy_enabled"`
	GithubIntegrationUUID    string           `json:"github_integration_uuid"`
	DeployReviewAppsEnabled  bool             `json:"deploy_review_apps_enabled"`
	DestroyOnCloseEnabled    bool             `json:"delete_on_close_enabled"`
	DestroyOnStaleEnabled    bool             `json:"delete_stale_enabled"`
	HoursBeforeDeleteOnClose uint             `json:"hours_before_delete_on_close"`
	HoursBeforeDeleteStale   uint             `json:"hours_before_delete_stale"`
	LastAutoDeployAt         time.Time        `json:"last_auto_deploy_at"`
}
```

Notice the `GithubBranch` field

While the API seems to use the following serializer for `scmRepoLinksController#update` action:

```ruby
class ScmRepoLinkSerializer < ActiveModel::Serializer
  attributes :id, :app_id, :linker, :url, :owner, :repo, :branch, :scm_type,
    :created_at, :updated_at, :auto_deploy_enabled, :auth_integration_uuid,
    :deploy_review_apps_enabled, :delete_on_close_enabled,
    :hours_before_delete_on_close, :delete_stale_enabled,
    :hours_before_delete_stale, :last_auto_deploy_at

  def id
    object._id.to_s
  end

  def app_id
    object.app_id.to_s
  end

  def linker
    {username: object.linker_username, email: object.linker_email, id: object.linker.uuid}
  end
end

```

There is no `github_branch` attribute here, only `branch`.

Could that be related?
